name: pyclass
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - xarray
  - requests
  - pandas
  - xlrd
  - gdal
  - geopandas
  - rtree
  - descartes
  - scipy
  - pyproj>=2.0
  - rasterio>=1.0
  - rasterstats
  - pyshp
  - pip
  - pip:
    - flopy
